name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
      if: hashFiles('package-lock.json') != ''
    
    - name: Setup Node.js (no cache)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
      if: hashFiles('package-lock.json') == ''
    
    - name: Install dependencies
      run: |
        if [ -f "package-lock.json" ]; then
          npm ci
        else
          npm install
        fi
    
    - name: Check manifest.json
      run: |
        if [ ! -f "src/manifest.json" ]; then
          echo "src/manifest.json not found"
          exit 1
        fi
        echo "Validating manifest.json structure..."
        # Basic JSON validation using jq
        cat src/manifest.json | jq . > /dev/null || (echo "Invalid JSON in manifest.json" && exit 1)
        echo "✅ manifest.json is valid JSON"
    
    - name: Check HTML syntax
      run: npm run lint:html
    
    - name: Check JavaScript syntax
      run: npm run lint:js
      
    - name: Run Prettier check
      run: npm run format:check
      
    - name: Build extension
      run: npm run build
      
    - name: Package extension
      run: |
        npm run package:chrome
        npm run package:firefox
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extension-packages
        path: |
          vivekananda-search-chrome.zip
          vivekananda-search-firefox.zip
